# https://docs.travis-ci.com/user/languages/android
language: android
android:
    components:
        # https://github.com/travis-ci/travis-ci/issues/5036
        - tools
        - platform-tools
        - build-tools-23.0.3
        - android-23
        - extra-android-m2repository
        - extra-google-m2repository

# Necessary because otherwise Gradle will OOM during the compilation phase:
# https://travis-ci.org/firebase/firebase-jobdispatcher-android/builds/164194294
env:
    - GRADLE_OPTS="-XX:MaxPermSize=8096m"
